### PR TITLE
gltf: Create a default sampler when missing

### LINKED ISSUE #451: [glTF] Use a default sampler when none is specified
Using `scene::GltfLoader`, some models in [glTF-Sample-Assets](https://github.com/KhronosGroup/glTF-Sample-Assets) fail to load because `texture.sampler` is not provided.

From the spec [3.8.2](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#textures):

> When texture.sampler is undefined, a sampler with repeat wrapping (in both directions) and auto filtering MUST be used.

This would allow us to load more models like:

- [WaterBottle](https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/WaterBottle)
- [BoomBox](https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/BoomBox)
- [Avocado](https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/Avocado)
- [BarramundiFish](https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/BarramundiFish)
- [Lantern](https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/Lantern)

### PR DESCRIPTION
**Pull request by footballhead**
GLTF 2.0 spec 3.8.2 says: "When texture.sampler is undefined, a sampler with repeat wrapping (in both directions) and auto filtering MUST be used."

This allows us to load more glTF-Sample-Assets.

Fixes #451

image

image

image

image

image

### CODE REVIEW

File: src/ppx/scene/scene_gltf_loader.cpp [hunk 1]
```diff
@@ -359,6 +359,64 @@ ppx::Result ValidateAccessorIndexType(const cgltf_accessor* pGltfAccessor, grfx:
     return ppx::ERROR_SCENE_INVALID_SOURCE_GEOMETRY_INDEX_TYPE;
 }
 
+// The GLTF 2.0 spec 3.8.2 says "When texture.source is undefined, the image SHOULD be provided by
+// an extension or application-specific means, otherwise the texture object is undefined"
```
Comment (footballhead) [inline src/ppx/scene/scene_gltf_loader.cpp]: Wrong reference

```suggestion
// The GLTF 2.0 spec 3.8.2 says "When texture.sampler is undefined, a sampler with repeat wrapping
// (in both directions) and auto filtering MUST be used"
```

**Review by Keenuts — APPROVED** [review]
LGTM, thanks for the improvement!
